--  CREATE TABLE 테이블명(
--  컬럼명1 자료형(크기) 제약조건,
--  컬럼명2 자료형(크기) 제약조건,
--  ....);

CREATE TABLE STUDENT(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(15) NOT NULL,
    ADDR VARCHAR2(100),
    INDATE DATE DEFAULT SYSDATE,
    SCLASS VARCHAR2(50),
    SROOM NUMBER(3)
    );
    
DESC STUDENT;

SELECT * FROM STUDENT;

--INSERT INTO 테이블명(컬럼명1,컬럼병2,...)
--VALUES(값1,값2,....);
--COMMIT

INSERT INTO STUDENT(NO, NAME, TEL, ADDR, SCLASS, SROOM)
VALUES(1,'홍길동','010-1111','서울 마포구','자바반',101);

SELECT NO,NAME,TEL,SCLASS FROM STUDENT;

SELECT * FROM STUDENT;

INSERT INTO STUDENT(NO,NAME,TEL,ADDR)
VALUES(2,'김철수','010-2222','서울 강남구');

COMMIT;

INSERT INTO STUDENT
VALUES(3,'이영희','010-3333','서울 강동구',SYSDATE,'빅데이터반',201);
ROLLBACK;

--자바반학생 2명
INSERT INTO STUDENT
VALUES(4,'이철희','010-4444','서울 강서구',SYSDATE,'자바반',101);

INSERT INTO STUDENT
VALUES(5,'최윤희','010-5555','서울 강남구',SYSDATE,'자바반',101);
--빅데이터반 2명추가
INSERT INTO STUDENT
VALUES(6,'최철수','010-6666','서울 강동구',SYSDATE,'빅데이터반',201);

INSERT INTO STUDENT
VALUES(7,'김희철','010-7777','서울 마포구',SYSDATE,'빅데이터반',201);

COMMIT;
SELECT * FROM STUDENT
WHERE SCLASS='자바반';

--테이블삭제
--DROP TABLE 테이블명

DROP TABLE STUDENT;

--학급
--테이블명: SCLASS
--학급코드번호 : SNO NUMBER(4)
--학급명 : SNAME VARCHAR2(30)
--교실번호 : SROOM NUMBER(3)

CREATE TABLE SCLASS(
    SNO NUMBER(4) PRIMARY KEY,
    SNAME VARCHAR2(30) NOT NULL,
    SROOM NUMBER(3)
);
DESC SCLASS;

-- 학급정보를 3개 INSERT하기
--10 백엔드개발자반 101
--20 빅데이터반 201
--30 융복합반 301

INSERT INTO SCLASS(SNO,SNAME,SROOM)
VALUES(10,'백엔드개발자반',101);
INSERT INTO SCLASS
VALUES(20,'빅데이터반',201);
INSERT INTO SCLASS
VALUES(30,'융복합반',301);

SELECT * FROM SCLASS;

COMMIT;

--UPDATE 테이블명 SET 컬럼명 = 값
--WHERE 조건절
UPDATE SCLASS SET SNAME='백엔드개발자반';
--WHERE조건절 안주면 모든 SNAME컬럼값이 변경됨 무조건 WHERE 써야됨!
SELECT * FROM SCLASS;

ROLLBACK;

UPDATE SCLASS SET SNAME='백엔드개발자반'
WHERE SNAME='백엔드개발바반'; 
--SNAME이 '백엔드개발바반'인것을 백엔드개발자반으로 변경

CREATE TABLE STUDENT(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(15),
    ADDR VARCHAR2(100),
    INDATE DATE DEFAULT SYSDATE,
    SNO_FK NUMBER(4) REFERENCES SCLASS (SNO) -- 외래키 설정 데이터타입동일해야됨
);

DESC STUDENT;

--일련번호를 생성해주는 객체 : SEQUENCE

--CREATE SEQUENCE 시퀀스명
--START WITH 시작값
--INCREMENT BY 증가치
--NOCACHE;

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE; --원래 시퀀스를 만들면 메모리에 20개정도 캐시를 저장해두는데 그걸 안쓴다는뜻


INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'홍길동','1111','서울 강남구 삼성동',10);
INSERT INTO STUDENT
VALUES(STUDENT_SEQ.NEXTVAL,'김철수','2222','서울 마포구 서교동',SYSDATE,20);
SELECT * FROM STUDENT;

--10번학급 2명
INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'이기철','3111','서울 강남구 삼성동',10);
INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'이유진','3112','서울 강남구 삼성동',10);
--20번학급 2명
INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'김세연','4211','서울 강남구 삼성동',20);
INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'이진호','4441','서울 강남구 삼성동',20);
--30번학급 1명
INSERT INTO STUDENT(NO,NAME,TEL,ADDR,SNO_FK)
VALUES(STUDENT_SEQ.NEXTVAL,'최재훈','4133','서울 강남구 삼성동',30);

SELECT * FROM STUDENT;

--삭제
--DELETE FROM 테이블명 WHERE 조건;
DELETE FROM STUDENT
WHERE NO=2;
COMMIT;
--테이블 2개를 하나로 합쳐서 보여주자
-- JOIN문
--SELECT 테이블1.컬럼명1,...,테이블2.컬럼명...
--FROM 테이블명1 JOIN 테이블명2
--ON 테이블1.PK = 테이블2.FK
SELECT STUDENT.NO, NAME, TEL,INDATE, SNAME,SROOM
FROM SCLASS JOIN STUDENT
ON SCLASS.SNO = STUDENT.SNO_FK;

--학급별 인원수
SELECT COUNT(*) FROM STUDENT;


SELECT * FROM EMP;

--사원테이블에서 사번, 사원명, 급여를 가져와 보여주세요

SELECT EMPNO, ENAME, SAL FROM EMP;

--사원테이블에서 사번, 사원명, 급여, 500을 인상시킨 급여를 가져와 보여주세요

SELECT EMPNO, ENAME, SAL, SAL+500 AS SAL_UP FROM EMP;

SELECT EMPNO, ENAME, SAL, COMM FROM EMP;

SELECT EMPNO, ENAME, SAL, COMM , JOB ,
SAL*12 + NVL(COMM,0) AS YEAR_SAL FROM EMP;

--NVL

SELECT EMPNO, ENAME, MGR, NVL2(MGR,1,0) AS MGR2 FROM EMP;
COMMIT;