/* 회원 */
CREATE TABLE member (
	idx NUMBER(8) NOT NULL, /* 회원번호 */
	name VARCHAR2(30 BYTE) NOT NULL, /* 이름 */
	userid VARCHAR2(20 BYTE) NOT NULL, /* 아이디 */
	pwd VARCHAR2(16 BYTE) NOT NULL, /* 비밀번호 */
	hp1 CHAR(3 BYTE) NOT NULL, /* 연락처1 */
	hp2 CHAR(4 BYTE) NOT NULL, /* 연락처2 */
	hp3 CHAR(4 CHAR) NOT NULL, /* 연락처3 */
	post CHAR(5 CHAR), /* 우편번호 */
	addr1 VARCHAR2(100 BYTE), /* 주소1 */
	addr2 VARCHAR2(100 BYTE), /* 주소2 */
	indate DATE, /* 가입일 */
	mileage NUMBER(8), /* 적립금 */
	status NUMBER(2) /* 회원상태 */
);

COMMENT ON TABLE member IS '회원';

COMMENT ON COLUMN member.idx IS '회원번호';

COMMENT ON COLUMN member.name IS '이름';

COMMENT ON COLUMN member.userid IS '아이디';

COMMENT ON COLUMN member.pwd IS '비밀번호';

COMMENT ON COLUMN member.hp1 IS '연락처1';

COMMENT ON COLUMN member.hp2 IS '연락처2';

COMMENT ON COLUMN member.hp3 IS '연락처3';

COMMENT ON COLUMN member.post IS '우편번호';

COMMENT ON COLUMN member.addr1 IS '주소1';

COMMENT ON COLUMN member.addr2 IS '주소2';

COMMENT ON COLUMN member.indate IS '가입일';

COMMENT ON COLUMN member.mileage IS '적립금';

COMMENT ON COLUMN member.status IS '회원상태';

CREATE UNIQUE INDEX PK_member
	ON member (
		idx ASC
	);

ALTER TABLE member
	ADD
		CONSTRAINT PK_member
		PRIMARY KEY (
			idx
		);

/* 상품 */
CREATE TABLE product (
	PNUM NUMBER(8) NOT NULL, /* 상품번호 */
	DOWNCG_CODE NUMBER(8), /* 하위카테고리코드 */
	UPCG_CODE NUMBER(8), /* 상위카테고리코드 */
	PNAME VARCHAR2(50 BYTE) NOT NULL, /* 상품명 */
	PIMAGE1 VARCHAR2(50), /* 이미지1 */
	PIMAGE2 VARCHAR2(50), /* 이미지2 */
	PIMAGE3 VARCHAR2(50), /* 이미지3 */
	PRICE NUMBER(8) NOT NULL, /* 상품정가 */
	SALEPRICE NUMBER(8), /* 상품판매가 */
	PQTY NUMBER(8), /* 상품수량 */
	POINT NUMBER(8), /* 포인트 */
	PSPEC VARCHAR2(200 BYTE), /* 스펙 */
	PCONTENTS VARCHAR2(1000 BYTE), /* 상품설명 */
	PCOMPANY VARCHAR2(50 BYTE), /* 제조사 */
	PINDATE DATE /* 등록일 */
);

COMMENT ON TABLE product IS '상품';

COMMENT ON COLUMN product.PNUM IS '상품번호';

COMMENT ON COLUMN product.DOWNCG_CODE IS '하위카테고리코드';

COMMENT ON COLUMN product.UPCG_CODE IS '상위카테고리코드';

COMMENT ON COLUMN product.PNAME IS '상품명';

COMMENT ON COLUMN product.PIMAGE1 IS '이미지1';

COMMENT ON COLUMN product.PIMAGE2 IS '이미지2';

COMMENT ON COLUMN product.PIMAGE3 IS '이미지3';

COMMENT ON COLUMN product.PRICE IS '상품정가';

COMMENT ON COLUMN product.SALEPRICE IS '상품판매가';

COMMENT ON COLUMN product.PQTY IS '상품수량';

COMMENT ON COLUMN product.POINT IS '포인트';

COMMENT ON COLUMN product.PSPEC IS '스펙';

COMMENT ON COLUMN product.PCONTENTS IS '상품설명';

COMMENT ON COLUMN product.PCOMPANY IS '제조사';

COMMENT ON COLUMN product.PINDATE IS '등록일';

CREATE UNIQUE INDEX PK_product
	ON product (
		PNUM ASC
	);

ALTER TABLE product
	ADD
		CONSTRAINT PK_product
		PRIMARY KEY (
			PNUM
		);

/* 상위카테고리 */
CREATE TABLE UPCATEGORY (
	UPCG_CODE NUMBER(8) NOT NULL, /* 상위카테고리코드 */
	UPCG_NAME VARCHAR2(30 BYTE) NOT NULL /* 하위카테고리명 */
);

COMMENT ON TABLE UPCATEGORY IS '상위카테고리';

COMMENT ON COLUMN UPCATEGORY.UPCG_CODE IS '상위카테고리코드';

COMMENT ON COLUMN UPCATEGORY.UPCG_NAME IS '하위카테고리명';

CREATE UNIQUE INDEX PK_UPCATEGORY
	ON UPCATEGORY (
		UPCG_CODE ASC
	);

ALTER TABLE UPCATEGORY
	ADD
		CONSTRAINT PK_UPCATEGORY
		PRIMARY KEY (
			UPCG_CODE
		);

/* 하위카테고리 */
CREATE TABLE DOWNCATEGORY (
	DOWNCG_CODE NUMBER(8) NOT NULL, /* 하위카테고리코드 */
	UPCG_CODE NUMBER(8) NOT NULL, /* 상위카테고리코드 */
	DOWNCG_NAME VARCHAR2(30 BYTE) NOT NULL /* 하위카테고리명 */
);

COMMENT ON TABLE DOWNCATEGORY IS '하위카테고리';

COMMENT ON COLUMN DOWNCATEGORY.DOWNCG_CODE IS '하위카테고리코드';

COMMENT ON COLUMN DOWNCATEGORY.UPCG_CODE IS '상위카테고리코드';

COMMENT ON COLUMN DOWNCATEGORY.DOWNCG_NAME IS '하위카테고리명';

CREATE UNIQUE INDEX PK_DOWNCATEGORY
	ON DOWNCATEGORY (
		DOWNCG_CODE ASC,
		UPCG_CODE ASC
	);

ALTER TABLE DOWNCATEGORY
	ADD
		CONSTRAINT PK_DOWNCATEGORY
		PRIMARY KEY (
			DOWNCG_CODE,
			UPCG_CODE
		);

/* 장바구니 */
CREATE TABLE CART (
	CARTNUM NUMBER(8) NOT NULL, /* 장바구니번호 */
	idx_FK NUMBER(8), /* 회원번호 */
	PNUM_FK NUMBER(8), /* 상품번호 */
	OQTY NUMBER(8), /* 수량 */
	INDATE DATE /* 등록일 */
);

COMMENT ON TABLE CART IS '장바구니';

COMMENT ON COLUMN CART.CARTNUM IS '장바구니번호';

COMMENT ON COLUMN CART.idx_FK IS '회원번호';

COMMENT ON COLUMN CART.PNUM_FK IS '상품번호';

COMMENT ON COLUMN CART.OQTY IS '수량';

COMMENT ON COLUMN CART.INDATE IS '등록일';

/* 후기게시판 */
CREATE TABLE REVIEW (
	NUM NUMBER(8) NOT NULL, /* 글번호 */
	idx NUMBER(8), /* 회원번호 */
	PNUM NUMBER(8), /* 상품번호 */
	TITLE VARCHAR2(200), /* 제목 */
	NAME VARCHAR2(30), /* 작성자 */
	CONTENT VARCHAR2(2000), /* 내용 */
	SCORE NUMBER(1), /* 평가점수 */
	WDATE DATE, /* 작성일 */
	FILENAME VARCHAR2(100) /* 업로드파일 */
);

COMMENT ON TABLE REVIEW IS '후기게시판';

COMMENT ON COLUMN REVIEW.NUM IS '글번호';

COMMENT ON COLUMN REVIEW.idx IS '회원번호';

COMMENT ON COLUMN REVIEW.PNUM IS '상품번호';

COMMENT ON COLUMN REVIEW.TITLE IS '제목';

COMMENT ON COLUMN REVIEW.NAME IS '작성자';

COMMENT ON COLUMN REVIEW.CONTENT IS '내용';

COMMENT ON COLUMN REVIEW.SCORE IS '평가점수';

COMMENT ON COLUMN REVIEW.WDATE IS '작성일';

COMMENT ON COLUMN REVIEW.FILENAME IS '업로드파일';

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		NUM ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			NUM
		);

/* 주문개요 */
CREATE TABLE ORDER_DESC (
	ONUM VARCHAR2(30) NOT NULL, /* 주문번호 */
	idx NUMBER(8) NOT NULL, /* 회원번호 */
	OTOTALPRICE NUMBER(10), /* 주문총액 */
	ORORALPOINT NUMBER(8), /* 지급포인트 */
	ORDERLIVER VARCHAR2(20 BYTE), /* 배송상태 */
	OPAYSTATE VARCHAR2(20 BYTE), /* 지불상태 */
	ORDERDATE DATE, /* 주문일 */
	ORDERMEMO VARCHAR2(200 BYTE), /* 배송시요청사항 */
	OPOINTUSE NUMBER(2) /* 적립금사용액 */
);

COMMENT ON TABLE ORDER_DESC IS '주문개요';

COMMENT ON COLUMN ORDER_DESC.ONUM IS '주문번호';

COMMENT ON COLUMN ORDER_DESC.idx IS '회원번호';

COMMENT ON COLUMN ORDER_DESC.OTOTALPRICE IS '주문총액';

COMMENT ON COLUMN ORDER_DESC.ORORALPOINT IS '지급포인트';

COMMENT ON COLUMN ORDER_DESC.ORDERLIVER IS '배송상태';

COMMENT ON COLUMN ORDER_DESC.OPAYSTATE IS '지불상태';

COMMENT ON COLUMN ORDER_DESC.ORDERDATE IS '주문일';

COMMENT ON COLUMN ORDER_DESC.ORDERMEMO IS '배송시요청사항';

COMMENT ON COLUMN ORDER_DESC.OPOINTUSE IS '적립금사용액';

CREATE UNIQUE INDEX PK_ORDER_DESC
	ON ORDER_DESC (
		ONUM ASC
	);

ALTER TABLE ORDER_DESC
	ADD
		CONSTRAINT PK_ORDER_DESC
		PRIMARY KEY (
			ONUM
		);

/* 주문상품 */
CREATE TABLE ORDER_PRODUCT (
	ONUM VARCHAR2(30) NOT NULL, /* 주문번호 */
	PNUM NUMBER(8) NOT NULL, /* 상품번호 */
	SALEPRICE NUMBER(10), /* 단가 */
	OQTY NUMBER(8), /* 수량 */
	PIMAGE VARCHAR2(50), /* 이미지1 */
	OPOINT NUMBER(8) /* 포인트 */
);

COMMENT ON TABLE ORDER_PRODUCT IS '주문상품';

COMMENT ON COLUMN ORDER_PRODUCT.ONUM IS '주문번호';

COMMENT ON COLUMN ORDER_PRODUCT.PNUM IS '상품번호';

COMMENT ON COLUMN ORDER_PRODUCT.SALEPRICE IS '단가';

COMMENT ON COLUMN ORDER_PRODUCT.OQTY IS '수량';

COMMENT ON COLUMN ORDER_PRODUCT.PIMAGE IS '이미지1';

COMMENT ON COLUMN ORDER_PRODUCT.OPOINT IS '포인트';

CREATE UNIQUE INDEX PK_ORDER_PRODUCT
	ON ORDER_PRODUCT (
		ONUM ASC,
		PNUM ASC
	);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT PK_ORDER_PRODUCT
		PRIMARY KEY (
			ONUM,
			PNUM
		);

/* 수령자 */
CREATE TABLE RECEIVER (
	ONUM VARCHAR2(30) NOT NULL, /* 주문번호 */
	NAME VARCHAR2(30) NOT NULL, /* 수령자명 */
	HP1 CHAR(3) NOT NULL, /* 연락처1 */
	HP2 CHAR(4) NOT NULL, /* 연락처2 */
	HP3 CHAR(4) NOT NULL, /* 연락처3 */
	POST CHAR(5) NOT NULL, /* 우편번호 */
	ADDR1 VARCHAR2(100) NOT NULL, /* 주소1 */
	ADDR2 VARCHAR2(100) NOT NULL /* 주소2 */
);

COMMENT ON TABLE RECEIVER IS '수령자';

COMMENT ON COLUMN RECEIVER.ONUM IS '주문번호';

COMMENT ON COLUMN RECEIVER.NAME IS '수령자명';

COMMENT ON COLUMN RECEIVER.HP1 IS '연락처1';

COMMENT ON COLUMN RECEIVER.HP2 IS '연락처2';

COMMENT ON COLUMN RECEIVER.HP3 IS '연락처3';

COMMENT ON COLUMN RECEIVER.POST IS '우편번호';

COMMENT ON COLUMN RECEIVER.ADDR1 IS '주소1';

COMMENT ON COLUMN RECEIVER.ADDR2 IS '주소2';

CREATE UNIQUE INDEX PK_RECEIVER
	ON RECEIVER (
		ONUM ASC
	);

ALTER TABLE RECEIVER
	ADD
		CONSTRAINT PK_RECEIVER
		PRIMARY KEY (
			ONUM
		);

ALTER TABLE product
	ADD
		CONSTRAINT FK_DOWNCATEGORY_TO_product
		FOREIGN KEY (
			DOWNCG_CODE,
			UPCG_CODE
		)
		REFERENCES DOWNCATEGORY (
			DOWNCG_CODE,
			UPCG_CODE
		);

ALTER TABLE product
	ADD
		CONSTRAINT FK_UPCATEGORY_TO_product
		FOREIGN KEY (
			UPCG_CODE
		)
		REFERENCES UPCATEGORY (
			UPCG_CODE
		);

ALTER TABLE DOWNCATEGORY
	ADD
		CONSTRAINT FK_UPCATEGORY_TO_DOWNCATEGORY
		FOREIGN KEY (
			UPCG_CODE
		)
		REFERENCES UPCATEGORY (
			UPCG_CODE
		);

ALTER TABLE CART
	ADD
		CONSTRAINT FK_member_TO_CART
		FOREIGN KEY (
			idx_FK
		)
		REFERENCES member (
			idx
		);

ALTER TABLE CART
	ADD
		CONSTRAINT FK_product_TO_CART
		FOREIGN KEY (
			PNUM_FK
		)
		REFERENCES product (
			PNUM
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_product_TO_REVIEW
		FOREIGN KEY (
			PNUM
		)
		REFERENCES product (
			PNUM
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_member_TO_REVIEW
		FOREIGN KEY (
			idx
		)
		REFERENCES member (
			idx
		);

ALTER TABLE ORDER_DESC
	ADD
		CONSTRAINT FK_member_TO_ORDER_DESC
		FOREIGN KEY (
			idx
		)
		REFERENCES member (
			idx
		);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT FK_ORDER_DESC_TO_ORDER_PRODUCT
		FOREIGN KEY (
			ONUM
		)
		REFERENCES ORDER_DESC (
			ONUM
		);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT FK_product_TO_ORDER_PRODUCT
		FOREIGN KEY (
			PNUM
		)
		REFERENCES product (
			PNUM
		);

ALTER TABLE RECEIVER
	ADD
		CONSTRAINT FK_ORDER_DESC_TO_RECEIVER
		FOREIGN KEY (
			ONUM
		)
		REFERENCES ORDER_DESC (
			ONUM
		);
-----테이블 생성 및 제약조건 추가-----
--create sequence MEMBER_IDX_SQ;


--status 값에따라 별칭을준 컬럼에 설정한 데이터를 삽입한 가상의 테이블을 만드는 명령어

select member.*, decode(status,0,'활동회원',-1,'정지회원',-2,'탈퇴회원') statusStr
from member;
-- 위에는 오라클에만되는것
select member.*,
case status
    when 0 then '활동회원'
    when -1 then '정지회원'
    when -2 then '탈퇴회원'
end as statusStr
from member;
-- case문이용 mysql도가능
select * from member;
--update member set status='-2' where idx=6;
--commit;

update member set status=9 where idx=1;
commit;

-- grant create view, create synonym to multi; >>system접속후 multi계정 뷰생성권한부여

--status값이 -1 보다 큰 회원들만 모아서 memberView를 생성하자
create or replace view memberView
as
select member.*, decode(status,0,'활동회원',-1,'정지회원',-2,'탈퇴회원',9,'관리자') statusStr
from member where status >-2;

select * from memberView;

---------------------------------------------------
create sequence product_seq nocache;